configured_endpoints: 29
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/stigg%2Fstigg-25aade8ade9b21ac22b5d1b548ab4785ce896e7e5954c64543adf6d3d2bde4a0.yml
openapi_spec_hash: acffa6e93f0c33afdad99d1a7d2f3c99
config_hash: 9ed39470163a5bdaf0df2f46bddeba7e
