configured_endpoints: 29
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/stigg%2Fstigg-8bbec7645f5c53cedd3c32cbe642f487bd076ee65b2755cdf85b82bc940abf4c.yml
openapi_spec_hash: 0a82f3f90b212ff44d937dbb879efbdf
config_hash: 9ed39470163a5bdaf0df2f46bddeba7e
