configured_endpoints: 29
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/stigg%2Fstigg-74ea1cb86de1c923649c6a06cbed9b15a9c9c8fdc5ab7a41d61179ec75c46ca3.yml
openapi_spec_hash: ea4bcd1db0173e5ab2aaf459f937bab3
config_hash: 9ed39470163a5bdaf0df2f46bddeba7e
