configured_endpoints: 31
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/stigg%2Fstigg-efd0cebb3fdbf122669e689b8ea2f30db7311072fe5fe9b4be7c3cc24ffaa77e.yml
openapi_spec_hash: 09dfb652ddfdfd1fa7c47e6b1ec1bafa
config_hash: 29c18a4b6ee2f5a3728e4808f0884238
