configured_endpoints: 2
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/stigg%2Fstigg-e496aead7cd3b63575013a893d232f518c95ce62ad92b6fb425fc1360bf0feef.yml
openapi_spec_hash: 1b914fbbffb8ee68b2e9e7e4ef6c3141
config_hash: 73eb50fad6f6d6f5b6dd5701ceeececc
