configured_endpoints: 29
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/stigg%2Fstigg-214a10aa3eb826418dcc3eabec8a37e228c65fefbf8bc7c1b9620a44bcbea7c4.yml
openapi_spec_hash: 247ad795368fa9ec49f1cd5e0f1d80f9
config_hash: 9ed39470163a5bdaf0df2f46bddeba7e
