configured_endpoints: 29
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/stigg%2Fstigg-0a80475384dbc36e1d1a79a843bcc0284a7ab4eddd84fd0e0ceba115d4fe557b.yml
openapi_spec_hash: bf8e1129b05fca903d93e39fdff43aa0
config_hash: 9ed39470163a5bdaf0df2f46bddeba7e
